language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
#    - TOX_ENV=py34
#    - TOX_ENV=pypy
    - TOX_ENV=docs
#    - TOX_ENV=pep8
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
# command to run tests
script: tox -e $TOX_ENV
branches:
  only:
    - master
notifications:
  hipchat: 7d72ba6ba0bf07248f17e0a6a1a899@DevOps