language: python
os:
- linux
- osx
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
env:
  global:
  - secure: EUpWmrnhHKPkz9cOGbEEwhBtUBRqtQ775ck042B8/pI9ZZZghbKl3Jm8ahpfms3JiZcHMCG06MBREs1ISK/g2OfHKsdULCg5g3UFXteVQo769kwh/x4lniSbU2eipcN0s9Q/Ak5zStwTa5aNQ4FU/3zSgTDxi/OcDKGXDbVwHD8=
  - secure: l/xwPJ01auD8LSRb9AaMXtqZ08uELw85zjnA/C3A72TvQip/zxrtlaFgSy7qEuMJxlSR8avNIhOeXNTwyU8WuSyn8E3OgLVbmiVwPO5w9Pt80Q34jrGxRO0HTpZY4YSJENDgV+IFswo9tMZx4qgQIcTHeADSHZgfY0cCQLaQ2Vk=
  - secure: Q+Wt1XCyIp5ykppxKWl9qi1G39w5u12wu8Sf8UxotzXHu/nOOqr9O8CHVy+moEElrwvqQGYbKzE3kRmy4OCTukMbTWfUYIQWYU7qKRURAyDYXceHRroPPdX8SmKxZyXqgSXEN46u2hWoi0EAJiWlN/J38ovQND/+hxT8dppJPXI=
  - secure: NHvQfaPAfQyWar87FmM2SWynOE2QaqgI4neX6aERey3kVZBsOdhPdmdnUBXvNd2BrfyfUuf1GOP2MGVXOAQ1Mg7MQ5ce85EufQgPqu3a/jum1J6GwO2tDOnYXlGGXwHbuTAyEKi9w8r5JRSz4cyY/H+iLTVd/ShjYAS8hOM5M1E=
  - secure: kCcRnV0K070zjFHwpUVM1kfKo2a8oK8eC2Xa4XEBtOdNAM/Ek+pLCM6zYgvD84ep9xv5I3XGOxHxsfqx/u25BuPvQ341p7VaGFJs2+K3OD0np/nyhfq3EBsCylthDxB/jXPqGw5X4QLcvSVucmQ9MIc/bwqV+E7eTIpccWr827Q=
install:
- pip -q install -r requirements.txt
- pip -q install -r requirements-dev.txt
- pip -q install -r requirements-opt.txt || echo "skipped"
- pip -q install coveralls
script:
- "./pretest"
- curl --silent -Lo travis_after_all.py https://raw.github.com/pycontribs/travis_after_all/master/travis_after_all.py
- travis_wait python setup.py test
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING..."
        else
          echo "Some jobs failed"
        fi
      fi
  - coveralls
  - python setup.py build_sphinx upload_docs release
after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
          echo "All jobs failed"
        else
          echo "Some jobs failed"
        fi
      fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
branches:
  only:
  - master
notifications:
  hipchat: 7d72ba6ba0bf07248f17e0a6a1a899@DevOps
deploy:
  provider: pypi
  user: sorin
  password:
    secure: "E0cjANF7SLBdYrsnWLK8X/xWznqkF0JrP/DVfDazPzUYH6ynFeneyofzNJQPLTLsqe1eKXhuUJ/Sbl+RHFB0ySo/j/7NfYd/9pm8hpUkGCvR09IwtvMLgWKp3k10NWab03o2GOkSJSrLvZofyZBGR40wwu2O9uXPCb2rvucCGbw="
  distributions: "sdist bdist_wheel"
  before_deploy:
  - echo "before deploy..."
  after_deploy:
  - echo "after deploy..."
